# Generated by Django 2.2.5 on 2020-04-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acknoledge_menu',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='acknoledge_menu',
            name='parent_ob',
        ),
    ]
