# Generated by Django 3.0.7 on 2020-07-14 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acknowledge', '0002_auto_20200714_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='graphDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('menu_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_submenudetail', to='acknowledge.acknoledge_menu')),
            ],
        ),
        migrations.CreateModel(
            name='graphDetailUsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('menu_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph_detail', to='acknowledge.graphDetail')),
                ('menu_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='graphDetailUser',
        ),
    ]
