# Generated by Django 2.2.5 on 2020-04-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0004_auto_20200426_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknoledge_menu',
            name='url_link',
            field=models.URLField(blank=True),
        ),
    ]
