# Generated by Django 3.0.7 on 2020-07-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0004_ack_submenupolicyfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_submenu',
            name='parent_ob',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='acknowledge.ack_submenu'),
        ),
    ]
