# Generated by Django 2.2.5 on 2020-04-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0005_auto_20200427_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_policypolicyfile',
            name='policies_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
