# Generated by Django 3.0.7 on 2020-07-19 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0005_auto_20200717_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ack_publicationname',
            old_name='publiction_name',
            new_name='submenu_name',
        ),
        migrations.RemoveField(
            model_name='ack_publicationname',
            name='file',
        ),
        migrations.RemoveField(
            model_name='ack_publicationname',
            name='folder_type',
        ),
        migrations.RemoveField(
            model_name='ack_publicationname',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='ack_publicationname',
            name='parent',
        ),
        migrations.AddField(
            model_name='ack_publicationname',
            name='folder_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ack_publicationname',
            name='publicationfile',
            field=models.FileField(blank=True, null=True, upload_to='publicattion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'JPEG', 'pdf', 'PDF'])]),
        ),
        migrations.AlterField(
            model_name='ack_publicationname',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acknowledge.ack_subpublicationmenu'),
        ),
        migrations.AlterField(
            model_name='ack_submenu',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='acknowledge.ack_submenu'),
        ),
    ]
