# Generated by Django 3.0.7 on 2020-07-19 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0006_auto_20200719_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_publicationname',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ack_publication_children', to='acknowledge.ack_subpublicationmenu'),
        ),
    ]
