# Generated by Django 3.0.7 on 2020-07-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0007_auto_20200719_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ack_publicationname',
            old_name='publicationfile',
            new_name='file',
        ),
    ]
