# Generated by Django 3.0.7 on 2020-07-20 19:13

import acknowledge.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0008_auto_20200719_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ack_guidelinesname',
            old_name='publiction_name',
            new_name='submenu_name',
        ),
        migrations.RemoveField(
            model_name='ack_guidelinesname',
            name='folder_type',
        ),
        migrations.RemoveField(
            model_name='ack_guidelinesname',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='ack_guidelinesname',
            name='parent',
        ),
        migrations.AddField(
            model_name='ack_guidelinesname',
            name='folder_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ack_guidelinesname',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='guidelines/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'JPEG']), acknowledge.models.newvalidate_image]),
        ),
        migrations.AlterField(
            model_name='ack_guidelinesname',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidelinesMenues', to='acknowledge.ack_subGuidelinesmenu'),
        ),
    ]
