# Generated by Django 2.2.5 on 2020-05-05 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0008_ack_policyname_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_submenu',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acknowledge.ack_submenu'),
        ),
    ]
