# Generated by Django 2.2.5 on 2020-05-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0009_ack_submenu_parent_ob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ack_submenu',
            name='parent_ob',
        ),
        migrations.AddField(
            model_name='ack_policyname',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acknowledge.ack_policyname'),
        ),
    ]
