# Generated by Django 2.2.5 on 2020-05-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0011_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_policyname',
            name='folder_type',
            field=models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two')], default=2),
        ),
        migrations.AddField(
            model_name='ack_policyname',
            name='menu_type',
            field=models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two')], default=1),
        ),
    ]
