# Generated by Django 3.0.7 on 2020-07-21 08:47

import acknowledge.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0011_auto_20200720_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ack_standardsname',
            old_name='publiction_name',
            new_name='submenu_name',
        ),
        migrations.RemoveField(
            model_name='ack_standardsname',
            name='folder_type',
        ),
        migrations.RemoveField(
            model_name='ack_standardsname',
            name='menu_type',
        ),
        migrations.RemoveField(
            model_name='ack_standardsname',
            name='parent',
        ),
        migrations.AddField(
            model_name='ack_standardsname',
            name='folder_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ack_standardsname',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='standards_file/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF', 'png', 'jpg', 'JPEG']), acknowledge.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='ack_standardsname',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standardFileMenues', to='acknowledge.ack_subStandardsmenu'),
        ),
    ]
