# Generated by Django 3.0.7 on 2020-07-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0013_auto_20200721_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphdetailused',
            name='menu_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graph_detail', to='acknowledge.graphDetail'),
        ),
    ]
