# Generated by Django 3.0.7 on 2020-07-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0014_auto_20200721_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ack_navyname',
            name='folder_type',
        ),
        migrations.RemoveField(
            model_name='ack_navyname',
            name='menu_type',
        ),
    ]
