# Generated by Django 2.2.5 on 2020-05-07 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0020_ack_subnhqe_librarylinesmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_subnavy_instructionssmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 14}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_subnavy_instructionmenues', to='acknowledge.acknoledge_menu'),
        ),
        migrations.AlterField(
            model_name='ack_subnavy_orderssmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 13}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_subnavy_ordersmenues', to='acknowledge.acknoledge_menu'),
        ),
        migrations.AlterField(
            model_name='ack_subnhqe_librarylinesmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 15}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_subnohqsmenues', to='acknowledge.acknoledge_menu'),
        ),
        migrations.AlterField(
            model_name='ack_substandardsmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 12}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_substandardsmenues', to='acknowledge.acknoledge_menu'),
        ),
    ]
