# Generated by Django 2.2.5 on 2020-05-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0023_auto_20200507_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_submenu',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
    ]
