# Generated by Django 2.2.5 on 2020-05-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0024_auto_20200509_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_policyname',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ack_policyname',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ack_policypolicyfile',
            name='added_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ack_policypolicyfile',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ack_publicationfile',
            name='added_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ack_publicationfile',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ack_publicationname',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ack_publicationname',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ack_subguidelinesmenu',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ack_subguidelinesmenu',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ack_submenu',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ack_subnavy_instructionssmenu',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ack_subnavy_instructionssmenu',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ack_subnavy_orderssmenu',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ack_subnavy_orderssmenu',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ack_subnhqe_librarylinesmenu',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ack_subnhqe_librarylinesmenu',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ack_subpublicationmenu',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ack_subpublicationmenu',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ack_substandardsmenu',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ack_substandardsmenu',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='acknoledge_menu',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='acknoledge_menu',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='acknowledge_parent_menu',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='acknowledge_parent_menu',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brsmenu',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='brsmenu',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
