# Generated by Django 2.2.5 on 2020-05-11 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0025_auto_20200509_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_subpublicationmenu',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publication/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF'])]),
        ),
    ]
