# Generated by Django 2.2.5 on 2020-05-11 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0026_ack_subpublicationmenu_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_subpublicationmenu',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publication/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF', 'png', 'jpg', 'JPEG'])]),
        ),
    ]
