# Generated by Django 2.2.5 on 2020-05-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0027_auto_20200511_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ack_subpublicationmenu',
            options={'ordering': ['-id']},
        ),
    ]
