# Generated by Django 2.2.5 on 2020-05-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0030_ack_subguidelinesmenu_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ack_subguidelinesmenu',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ack_submenu',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='ack_publicationname',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_name', to='acknowledge.ack_subpublicationmenu'),
        ),
    ]
