# Generated by Django 2.2.5 on 2020-05-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0033_auto_20200513_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ack_publicationname',
            old_name='policy_name',
            new_name='publiction_name',
        ),
    ]
