# Generated by Django 2.2.5 on 2020-05-13 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0034_auto_20200513_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_publicationname',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_name', to='acknowledge.ack_subpublicationmenu'),
        ),
    ]
