# Generated by Django 2.2.5 on 2020-05-13 17:14

import acknowledge.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0035_auto_20200513_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ack_subpublicationmenu',
            name='file',
        ),
        migrations.AddField(
            model_name='ack_publicationname',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='publication/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF', 'png', 'jpg', 'JPEG']), acknowledge.models.validate_image]),
        ),
    ]
