# Generated by Django 2.2.5 on 2020-05-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0042_auto_20200514_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ack_submenu',
            name='older_type',
        ),
    ]
