# Generated by Django 2.2.5 on 2020-05-14 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0043_remove_ack_submenu_older_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_subpublicationmenu',
            name='folder_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ack_subpublicationmenu',
            name='folder_type',
            field=models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two')], default=2),
        ),
        migrations.AddField(
            model_name='ack_subpublicationmenu',
            name='menu_type',
            field=models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two')], default=1),
        ),
        migrations.AddField(
            model_name='ack_subpublicationmenu',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acknowledge.ack_subpublicationmenu'),
        ),
    ]
