# Generated by Django 2.2.5 on 2020-05-14 21:32

import acknowledge.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0047_auto_20200514_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ack_substandardsmenu',
            old_name='guidelinefile',
            new_name='standardfile',
        ),
        migrations.AddField(
            model_name='ack_subnavy_orderssmenu',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='navy_ordersfile/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF', 'png', 'jpg', 'JPEG']), acknowledge.models.validate_image]),
        ),
        migrations.AddField(
            model_name='ack_subnavy_orderssmenu',
            name='folder_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ack_subnavy_orderssmenu',
            name='folder_type',
            field=models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two')], default=2),
        ),
        migrations.AddField(
            model_name='ack_subnavy_orderssmenu',
            name='menu_type',
            field=models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two')], default=1),
        ),
        migrations.AddField(
            model_name='ack_subnavy_orderssmenu',
            name='navyfile',
            field=models.FileField(blank=True, null=True, upload_to='navy_orders/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF', 'png', 'jpg', 'JPEG']), acknowledge.models.validate_image]),
        ),
        migrations.AddField(
            model_name='ack_subnavy_orderssmenu',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acknowledge.ack_subNavy_Orderssmenu'),
        ),
    ]
