# Generated by Django 2.2.5 on 2020-05-14 22:39

import acknowledge.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0049_auto_20200514_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_subnhqe_librarylinesmenu',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='elibraryfiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF', 'png', 'jpg', 'JPEG']), acknowledge.models.validate_image]),
        ),
        migrations.AddField(
            model_name='ack_subnhqe_librarylinesmenu',
            name='folder_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ack_subnhqe_librarylinesmenu',
            name='folder_type',
            field=models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two')], default=2),
        ),
        migrations.AddField(
            model_name='ack_subnhqe_librarylinesmenu',
            name='menu_type',
            field=models.SmallIntegerField(choices=[(1, 'One'), (2, 'Two')], default=1),
        ),
        migrations.AddField(
            model_name='ack_subnhqe_librarylinesmenu',
            name='navyinstructionfile',
            field=models.FileField(blank=True, null=True, upload_to='elibrary/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF', 'png', 'jpg', 'JPEG']), acknowledge.models.validate_image]),
        ),
        migrations.AddField(
            model_name='ack_subnhqe_librarylinesmenu',
            name='parent_ob',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acknowledge.ack_subNHQe_Librarylinesmenu'),
        ),
    ]
