# Generated by Django 2.2.5 on 2020-05-17 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0051_auto_20200515_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='ack_submenu',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='policy/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'PDF'])]),
        ),
    ]
