# Generated by Django 2.2.5 on 2020-05-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0052_ack_submenu_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_submenu',
            name='submenu_name',
            field=models.CharField(max_length=200),
        ),
    ]
