# Generated by Django 2.2.5 on 2020-05-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0054_auto_20200517_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ack_subpublicationmenu',
            old_name='pubfile',
            new_name='file',
        ),
    ]
