# Generated by Django 2.2.5 on 2020-05-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0055_auto_20200517_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ack_subpublicationmenu',
            old_name='file',
            new_name='publicationfile',
        ),
    ]
