# Generated by Django 2.2.5 on 2020-05-17 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0056_auto_20200517_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_subpublicationmenu',
            name='publicationfile',
            field=models.FileField(blank=True, null=True, upload_to='publicattion/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'JPEG'])]),
        ),
    ]
