# Generated by Django 2.2.5 on 2020-06-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0058_auto_20200603_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ack_subguidelinesmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_subguidelinesmenues', to='acknowledge.acknoledge_menu'),
        ),
        migrations.AlterField(
            model_name='ack_submenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_submenues', to='acknowledge.acknoledge_menu'),
        ),
        migrations.AlterField(
            model_name='ack_subnavy_instructionssmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 6}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_subnavy_instructionmenues', to='acknowledge.acknoledge_menu'),
        ),
        migrations.AlterField(
            model_name='ack_subnavy_orderssmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_subnavy_ordersmenues', to='acknowledge.acknoledge_menu'),
        ),
        migrations.AlterField(
            model_name='ack_subnhqe_librarylinesmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 7}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_subnohqsmenues', to='acknowledge.acknoledge_menu'),
        ),
        migrations.AlterField(
            model_name='ack_subpublicationmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_subpublicationmenues', to='acknowledge.acknoledge_menu'),
        ),
        migrations.AlterField(
            model_name='ack_substandardsmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ask_substandardsmenues', to='acknowledge.acknoledge_menu'),
        ),
        migrations.AlterField(
            model_name='brsmenu',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'id': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brsmenues', to='acknowledge.acknoledge_menu'),
        ),
    ]
