# Generated by Django 2.2.5 on 2020-06-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acknowledge', '0061_tweet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followings', to='acknowledge.UserProfile')),
                ('to_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_followers', to='acknowledge.UserProfile')),
            ],
        ),
    ]
